name: Autograder Workflow

on: [push, pull_request]

jobs:
  run-autograder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API script (api.py)
      run: |
        python api.py &  # Ejecuta api.py en segundo plano

    - name: Run tests (test.py)
      run: |
        python test.py  # Ejecuta test.py para calificar api.py
